### ISSUE TITLE
#1 routes/index.js

### ISSUE THREAD

**Issue by Siwon-Kim** [Siwon-Kim/voyage-blog#1]
routes/index.js 폴더에는 보통 어떤 라우터 미들웨어가 들어가는 지 궁금합니다.

**Comment by Yunjaejo** [comment]
안녕하세요 시원님! 과제하시느라 너무 고생하셨습니다.
통상 index router에는 모든 도메인의 라우터가 연결되어 있습니다. 유저, 게시글, 댓글 등등의 라우터들이 모두 index로 모이고 app.js에서 index router만 import하여 좀 더 깔끔하게 앱파일을 만들 수 있습니다.

**Comment by Siwon-Kim** [comment]
아하! 설명 감사합니다 :) 참고해서 다음 과제도 진행해보겠습니다~
