### ISSUE TITLE
#2 Collection.find({}).sort({}).exec()에서 exec()

### ISSUE THREAD

**Issue by Siwon-Kim** [Siwon-Kim/voyage-blog#2]
숙련 강의를 듣다 해당 프로젝트에 관련해서 질문이 생겼습니다! 
posts GET API 내에서 `const posts = await Posts.find({}).sort({ createdAt: "desc" });`를 통해 post들을 불러왔는데 `exec()` 함수가 뒤에 꼭 붙어야 하는 건가요? 
찾아보니 exec()가 Promise를 반환해서 에러 핸들링에 좋다고 하는데 항상 이렇게 db query문에서 exec() 함수를 붙이는지 궁금합니다.

**Comment by Yunjaejo** [comment]
exec() 을 붙이지 않아도 동작은 잘 합니다. 하지만 Promise를 리턴하는게 에러 체크에 더 용이합니다.
https://mongoosejs.com/docs/promises.html
공식문서를 살펴보시면 exec() 유무에 따른 에러 예시를 볼 수 있습니다!

**Comment by Siwon-Kim** [comment]
네! 감사합니다 👍
